<?xml version="1.0" encoding="utf-8"?><Database Name="Pricegrabber" Class="PriceGrabberDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Pricegrabber;Integrated Security=True" SettingsObjectName="PriceGrabberConsole.Properties.Settings" SettingsPropertyName="PricegrabberConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Notification" Member="Notifications">
    <Type Name="Notification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>